use super::report::ReportMessage;

use crate::util::span::Span;

// todo (?): #1
//
// how these errors are handle by the parser

pub enum SyntaxKind {
  /// generated by the parser when it encounters a token (or EOF) it did not
  InvalidToken(Span),

  /// generated by the parser when it encounters an EOF it did not expect.
  UnrecognizedEOF(Span, String),

  /// the unexpected token: generated by the parser when
  /// it encounters a token it did not expect.
  UnrecognizedToken(Span, String),

  /// generated by the parser when it encounters additional, unexpected tokens.
  ExtraToken(Span, String),

  /// Custom error type.
  User(String),
}

pub fn write_syntax_report(kind: &SyntaxKind) -> ReportMessage {
  use super::report::{ReportKind, REPORT_ERROR};

  use crate::util::color::Color;

  use ariadne::Fmt;

  match kind {
    SyntaxKind::InvalidToken(span) => (
      ReportKind::Error(REPORT_ERROR),
      format!("{}", "invalid character".fg(Color::title())),
      vec![(
        *span,
        format!("{}", "this character does not ring a bell".fg(Color::error())),
        Color::error(),
      )],
      vec![format!("{}", "🤖 what language are you trying to speak to me in? i only speak zhoo")],
      vec![format!("{}", "👉 please go read the doc: <doc-link>".fg(Color::help()))]
    ),
    // todo #1
    SyntaxKind::UnrecognizedEOF(_span, _eof) => (
      ReportKind::Error(REPORT_ERROR),
      format!("{}", "unrecognized eof".fg(Color::title())),
      vec![],
      vec![],
      vec![]
    ),
    SyntaxKind::UnrecognizedToken(span, expected) => (
      ReportKind::Error(REPORT_ERROR),
      format!("{}", "unrecognized character".fg(Color::title())),
      vec![(
        *span,
        format!("{}", "um... i can't do anything with this character.".fg(Color::error())),
        Color::error(),
      )],
      vec![format!(
        "{}",
        "🤖 in other languages this character is valid but the zhoo syntax does not recognize it."
      )],
      vec![format!("👉 {}", format_args!("expected one of {expected}").fg(Color::help()))],
    ),
    // todo #1
    SyntaxKind::ExtraToken(_span, _unexpected) => (
      ReportKind::Error(REPORT_ERROR),
      format!("{}", "extra token".fg(Color::title())),
      vec![],
      vec![],
      vec![]
    ),
    // todo #1
    SyntaxKind::User(error) => (
      ReportKind::Error(REPORT_ERROR),
      format!("{}", error.fg(Color::title())),
      vec![],
      vec![],
      vec![]
    ),
  }
}
